### ISSUE TITLE
All scheduled  calls  are  sent  to  the  users  3  times

### ISSUE THREAD

**Issue by AnnetKabuye** [johnsonandjohnson/openmrs-distro-cfl#2]
@pwargulak please  note  that each scheduled  call is  sent  out  3  times for example if  I  schedule  for  a call  at  3:00pm the patient  is  called  at  3:00pm, 3:30pm  and  4:00pm even  when  they  successfully  complete  the  first  call  at  3:00pm.  Initially  calls  would  be  sent  out  3  times only for  users  who  missed  a  call  or  did  not  complete  the  call  successfully.  However,  at  the  moment  all  users  even  **those  that  have  completed their  calls  successfully**  are  receiving  calls  thrice.  

Please  advise  on where  we  can review  the  code or  make  changes to  configurations  to  be  able  to  resolve  this  issue. 

@sherrif10

Thanks,
Annet

**Comment by pwargulak** [comment]
Hi @AnnetKabuye 

There are GPs:
- messages.maxNumberOfAttempts
- messages.timeIntervalToNextReschedule

The Message Deliveries Job Task schedules the executions of Message Services for the next job execution interval. 
Single scheduled execution of multiple message services for a single Patient is called Scheduled Service Group (messages_scheduled_service_group).
The Scheduled Service Group consists of Scheduled Services (messages_scheduled_service) - each describes an execution of a single Message Service.
So for Patient which needs to receive Visit Reminder and Health Tip at tomorrow at 10:00, the Job creates one Scheduled Service Group for 10 o'clock with two Scheduled Services - one for Visit Reminder and one for Health Tip.

When the time comes for Scheduled Service Group to be executed, a call is made. The app follows CallFlow Design. There are CallFlow Design Steps like: ask phone call recipient for PIN, check the PIN, play Health Tip message to the call recipient, **mark Scheduled Service for Health Tip message as delivered**, play (or use text-to-speech) information about next visit, **mark Scheduled Service for visit information as delivered**, end the call.
Then the call ends and rescheduling logic is executed.

The rescheduling logic checks if the recently executed Scheduled Service Group has any Scheduled Services which are not marked as delivered. If there are not delivered Scheduled Services, then Scheduled Service Group is scheduled again including only not delivered Scheduled Services.

I think the issue is with the marking Scheduled Service as delivered during a phone call. 
Please check the _messages_scheduled_service_ DB table, _status_ column - I expect you will see value _PENDING_ for all Scheduled Services, even that which has been already executed and calls have been made.
The correct content would be that, all Scheduled Service which already happened are marked as DELIVERED.

Check the CallFflow Designs scripts, search for code which calls _register*_ methods of [MessagingService](https://github.com/johnsonandjohnson/openmrs-module-messages/blob/394c7d30e81a898cdb90b505f8952dab85cc1021/api/src/main/java/org/openmrs/module/messages/api/service/MessagingService.java).
For example, we have VisitRemindereFlow, that have play-reminder-handler step, that has script which contains: 
$messagesService.registerAttempt($visitReminderMessageId, 'DELIVERED', $DateUtil.now(), $callId) - it marks the Scheduled Service for Visit Reminder as delivered.

Best regards,
PiotrW

**Comment by sherrif10** [comment]
Thanks @pwargulak . cc @AnnetKabuye

**Comment by AnnetKabuye** [comment]
@pwargulak,  Thank  you  for  the  detailed response.  We  have  been  able  to  resolve  our  issue.
